matrix:
  include:
    - language: python
      python:
        - 2.7
        - 3.5
        - 3.6
        - 3.7
      before_script:
        - cd python
      script:
        - python sd01.py

    - language: go
      go:
        - "1.10.x"
      before_script:
        - cd go
      script:
        - go test
